version: "3.9"

services:
  web:
    build: .
    container_name: pgp_app
    command: sh -c "flask db_init && flask run --host=0.0.0.0 --port=5000"
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/pgp_auth
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: pgp_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgp_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pgp_auth"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  postgres_data:
